name: 'Publish Extension To Marketplace'
description: 'Publishes a extension to Marketplace'
inputs:
  VSCE_PAT:
    description: 'Azure PAT token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Publish Extension To Marketplace
      shell: bash
      env:
        NODE_ENV: production
        VSCE_PAT: ${{ inputs.VSCE_PAT }}
      run: npm run publish:extension
