name: Version Bump Package
description: Version bumps a package, adds git commit, adds git tag, and pushes to remote
inputs:
  SEMVER:
    description: patch, minor, major
    default: patch
  WORKING_DIRECTORY:
    description: working-directory to run publish from
    required: false

runs:
  using: composite
  steps:
    - name: Set Up Git
      shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Set SEMVER Patch
      shell: bash
      if: ${{ inputs.SEMVER == 'patch' }}
      run: echo "SEMVER=patch" >> $GITHUB_ENV

    - name: Set SEMVER Minor
      shell: bash
      if: ${{ inputs.SEMVER == 'minor' }}
      run: echo "SEMVER=minor" >> $GITHUB_ENV

    - name: Set SEMVER Major
      shell: bash
      if: ${{ inputs.SEMVER == 'major' }}
      run: echo "SEMVER=major" >> $GITHUB_ENV

    - name: Check SEMVER
      shell: bash
      if: ${{ env.SEMVER == '' }}
      run: |
        echo "Invalid SEMVER inputs.SEMVER Must be one of: patch, minor, major."
        exit 1

    - name: Set WORKING_DIRECTORY
      shell: bash
      if: ${{ inputs.WORKING_DIRECTORY == 'chathy' }}
      run: echo "WORKING_DIRECTORY=chathy" >> $GITHUB_ENV

    - name: Bump Version ${{ env.SEMVER }}
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm version $SEMVER --no-git-tag-version

    - name: Create Git Tag For Version
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        SUBTAG="${WORKING_DIRECTORY:-extension}"
        VERSION="$(npm pkg get version | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)"
        TAG="v${VERSION}-${SUBTAG}"
        LAST_TAG="$(git tag --list "*-${SUBTAG}" --sort=-creatordate | head -n1)"

        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "SUBTAG=$SUBTAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

    - name: Update CHANGELOG.md
      shell: bash
      run: |
        DATE=$(date +%Y-%m-%d)

        if [ -z "$LAST_TAG" ]; then
          COMMITS="$(git log --pretty=format:'- %s' --no-merges -- $WORKING_DIRECTORY)"
          COMMITS="${COMMITS:-First release}"
        else
          COMMITS="$(git log "${LAST_TAG}..HEAD" --pretty=format:'- %s' --no-merges -- $WORKING_DIRECTORY)"
          COMMITS="${COMMITS:-No new commits since ${LAST_TAG}}"
        fi

        echo "DATE=$DATE" >> $GITHUB_ENV

        cat >> CHANGELOG.md << EOF

        ## [${TAG}] - ${DATE}

        ### Changed
        ${COMMITS}
        EOF

    - name: Push changes
      shell: bash
      run: |
        git add .
        git commit -m "Bump version to ${TAG}"
        git tag -a "${TAG}" -m "Version bump ${TAG}"
        git push origin HEAD
        git push origin --tags
