name: Publish NPM
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      ACCESS:
        type: choice
        required: true
        default: 'pre-release'
        options:
          - default
          - private
          - public
      APPEND_TAG:
        type: choice
        required: true
        default: 'pre-release'
        options:
          - latest
          - next
          - pre-release
      REF:
        description: 'The branch, tag or SHA to checkout for publishing'
        required: true
        default: 'main'
      SEMVER:
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
      WORKING_DIRECTORY:
        description: 'The working directory to run the publish command from'
        required: true
        default: 'chathy'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.REF }}
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        uses: ./.github/actions/test

      - name: Version Bump Package
        uses: ./.github/actions/version_bump
        with:
          SEMVER: ${{ inputs.SEMVER }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}

      - name: Publish ${{ inputs.WORKING_DIRECTORY }} @ ${{ inputs.ref }}
        uses: ./.github/actions/publish_npm
        with:
          ACCESS: ${{ inputs.ACCESS }}
          APPEND_TAG: ${{ inputs.APPEND_TAG }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
